#pragma line 1 "hls_demo/.settings/adder.c" ::: -10
#pragma line 1 "hls_demo/.settings/adder.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 279 "/opt/Xilinx/Vivado_HLS/2015.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 6 "<command line>" 2 ::: 180
#pragma line 1 "<built-in>" 2 ::: 181
#pragma line 1 "hls_demo/.settings/adder.c" 2 ::: 182
#pragma line 1 "hls_demo/.settings/adder.h" 1 ::: 183
#pragma line 2 "hls_demo/.settings/adder.c" 2 ::: 187
#pragma line 5 "hls_demo/.settings/adder.c" ::: 193
#pragma line 10 "hls_demo/.settings/adder.c" ::: 201
#pragma line 11 "hls_demo/.settings/adder.c" ::: 205
#pragma line 12 "hls_demo/.settings/adder.c" ::: 209
