// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _fir_HH_
#define _fir_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "fir_mul_32s_32s_32_3.h"

namespace ap_rtl {

struct fir : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<32> > y;
    sc_out< sc_logic > y_ap_vld;
    sc_out< sc_lv<4> > c_address0;
    sc_out< sc_logic > c_ce0;
    sc_in< sc_lv<32> > c_q0;
    sc_in< sc_lv<32> > x;
    sc_in< sc_logic > x_ap_vld;


    // Module declarations
    fir(sc_module_name name);
    SC_HAS_PROCESS(fir);

    ~fir();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    fir_mul_32s_32s_32_3<1,3,32,32,32>* fir_mul_32s_32s_32_3_U1;
    fir_mul_32s_32s_32_3<1,3,32,32,32>* fir_mul_32s_32s_32_3_U2;
    fir_mul_32s_32s_32_3<1,3,32,32,32>* fir_mul_32s_32s_32_3_U3;
    fir_mul_32s_32s_32_3<1,3,32,32,32>* fir_mul_32s_32s_32_3_U4;
    fir_mul_32s_32s_32_3<1,3,32,32,32>* fir_mul_32s_32s_32_3_U5;
    fir_mul_32s_32s_32_3<1,3,32,32,32>* fir_mul_32s_32s_32_3_U6;
    fir_mul_32s_32s_32_3<1,3,32,32,32>* fir_mul_32s_32s_32_3_U7;
    fir_mul_32s_32s_32_3<1,3,32,32,32>* fir_mul_32s_32s_32_3_U8;
    fir_mul_32s_32s_32_3<1,3,32,32,32>* fir_mul_32s_32s_32_3_U9;
    fir_mul_32s_32s_32_3<1,3,32,32,32>* fir_mul_32s_32s_32_3_U10;
    fir_mul_32s_32s_32_3<1,3,32,32,32>* fir_mul_32s_32s_32_3_U11;
    sc_signal< sc_lv<16> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_32;
    sc_signal< sc_lv<32> > x_in_sig;
    sc_signal< sc_lv<32> > x_preg;
    sc_signal< sc_logic > x_ap_vld_in_sig;
    sc_signal< sc_logic > x_ap_vld_preg;
    sc_signal< sc_lv<32> > shift_reg_9;
    sc_signal< sc_lv<32> > shift_reg_8;
    sc_signal< sc_lv<32> > shift_reg_7;
    sc_signal< sc_lv<32> > shift_reg_6;
    sc_signal< sc_lv<32> > shift_reg_5;
    sc_signal< sc_lv<32> > shift_reg_4;
    sc_signal< sc_lv<32> > shift_reg_3;
    sc_signal< sc_lv<32> > shift_reg_2;
    sc_signal< sc_lv<32> > shift_reg_1;
    sc_signal< sc_lv<32> > shift_reg_0;
    sc_signal< sc_lv<32> > reg_189;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_73;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_bdd_80;
    sc_signal< sc_logic > ap_sig_cseq_ST_st9_fsm_8;
    sc_signal< bool > ap_sig_bdd_88;
    sc_signal< sc_logic > ap_sig_cseq_ST_st12_fsm_11;
    sc_signal< bool > ap_sig_bdd_96;
    sc_signal< sc_lv<32> > reg_193;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_bdd_105;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_6;
    sc_signal< bool > ap_sig_bdd_112;
    sc_signal< sc_lv<32> > reg_197;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_bdd_121;
    sc_signal< sc_logic > ap_sig_cseq_ST_st10_fsm_9;
    sc_signal< bool > ap_sig_bdd_128;
    sc_signal< sc_lv<32> > reg_201;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_bdd_137;
    sc_signal< sc_logic > ap_sig_cseq_ST_st11_fsm_10;
    sc_signal< bool > ap_sig_bdd_144;
    sc_signal< sc_lv<32> > grp_fu_209_p2;
    sc_signal< sc_lv<32> > tmp_6_reg_452;
    sc_signal< sc_lv<32> > grp_fu_225_p2;
    sc_signal< sc_lv<32> > tmp_6_1_reg_457;
    sc_signal< sc_lv<32> > tmp1_fu_279_p2;
    sc_signal< sc_lv<32> > tmp1_reg_487;
    sc_signal< sc_lv<32> > c_load_6_reg_492;
    sc_signal< sc_logic > ap_sig_cseq_ST_st8_fsm_7;
    sc_signal< bool > ap_sig_bdd_186;
    sc_signal< sc_lv<32> > grp_fu_241_p2;
    sc_signal< sc_lv<32> > tmp_6_2_reg_502;
    sc_signal< sc_lv<32> > grp_fu_257_p2;
    sc_signal< sc_lv<32> > tmp_6_3_reg_507;
    sc_signal< sc_lv<32> > grp_fu_273_p2;
    sc_signal< sc_lv<32> > tmp_6_4_reg_512;
    sc_signal< sc_lv<32> > tmp2_fu_334_p2;
    sc_signal< sc_lv<32> > tmp2_reg_542;
    sc_signal< sc_lv<32> > grp_fu_293_p2;
    sc_signal< sc_lv<32> > tmp_6_5_reg_552;
    sc_signal< sc_lv<32> > grp_fu_309_p2;
    sc_signal< sc_lv<32> > tmp_6_6_reg_557;
    sc_signal< sc_lv<32> > grp_fu_324_p2;
    sc_signal< sc_lv<32> > tmp_6_7_reg_562;
    sc_signal< sc_logic > ap_sig_cseq_ST_st13_fsm_12;
    sc_signal< bool > ap_sig_bdd_223;
    sc_signal< sc_lv<32> > tmp6_fu_383_p2;
    sc_signal< sc_lv<32> > tmp6_reg_582;
    sc_signal< sc_lv<32> > grp_fu_349_p2;
    sc_signal< sc_lv<32> > tmp_6_8_reg_587;
    sc_signal< sc_logic > ap_sig_cseq_ST_st15_fsm_14;
    sc_signal< bool > ap_sig_bdd_241;
    sc_signal< sc_lv<32> > grp_fu_365_p2;
    sc_signal< sc_lv<32> > tmp_6_9_reg_592;
    sc_signal< sc_lv<32> > grp_fu_377_p2;
    sc_signal< sc_lv<32> > tmp_6_s_reg_597;
    sc_signal< sc_logic > ap_sig_cseq_ST_st16_fsm_15;
    sc_signal< bool > ap_sig_bdd_274;
    sc_signal< sc_lv<32> > grp_fu_209_p0;
    sc_signal< sc_lv<32> > grp_fu_209_p1;
    sc_signal< sc_lv<32> > grp_fu_225_p0;
    sc_signal< sc_lv<32> > grp_fu_225_p1;
    sc_signal< sc_lv<32> > grp_fu_241_p0;
    sc_signal< sc_lv<32> > grp_fu_241_p1;
    sc_signal< sc_lv<32> > grp_fu_257_p0;
    sc_signal< sc_lv<32> > grp_fu_257_p1;
    sc_signal< sc_lv<32> > grp_fu_273_p0;
    sc_signal< sc_lv<32> > grp_fu_273_p1;
    sc_signal< sc_lv<32> > grp_fu_293_p0;
    sc_signal< sc_lv<32> > grp_fu_293_p1;
    sc_signal< sc_lv<32> > grp_fu_309_p0;
    sc_signal< sc_lv<32> > grp_fu_309_p1;
    sc_signal< sc_lv<32> > grp_fu_324_p0;
    sc_signal< sc_lv<32> > grp_fu_324_p1;
    sc_signal< sc_lv<32> > tmp3_fu_330_p2;
    sc_signal< sc_lv<32> > grp_fu_349_p0;
    sc_signal< sc_lv<32> > grp_fu_349_p1;
    sc_signal< sc_lv<32> > grp_fu_365_p0;
    sc_signal< sc_lv<32> > grp_fu_365_p1;
    sc_signal< sc_lv<32> > grp_fu_377_p0;
    sc_signal< sc_lv<32> > grp_fu_377_p1;
    sc_signal< sc_lv<32> > tmp8_fu_395_p2;
    sc_signal< sc_lv<32> > tmp7_fu_399_p2;
    sc_signal< sc_lv<32> > tmp5_fu_391_p2;
    sc_signal< sc_lv<32> > tmp4_fu_404_p2;
    sc_signal< sc_lv<32> > tmp_fu_387_p2;
    sc_signal< sc_logic > grp_fu_209_ce;
    sc_signal< sc_logic > grp_fu_225_ce;
    sc_signal< sc_logic > grp_fu_241_ce;
    sc_signal< sc_logic > grp_fu_257_ce;
    sc_signal< sc_logic > grp_fu_273_ce;
    sc_signal< sc_logic > grp_fu_293_ce;
    sc_signal< sc_logic > grp_fu_309_ce;
    sc_signal< sc_logic > grp_fu_324_ce;
    sc_signal< sc_logic > grp_fu_349_ce;
    sc_signal< sc_logic > ap_sig_cseq_ST_st14_fsm_13;
    sc_signal< bool > ap_sig_bdd_361;
    sc_signal< sc_logic > grp_fu_365_ce;
    sc_signal< sc_logic > grp_fu_377_ce;
    sc_signal< sc_lv<16> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<16> ap_ST_st1_fsm_0;
    static const sc_lv<16> ap_ST_st2_fsm_1;
    static const sc_lv<16> ap_ST_st3_fsm_2;
    static const sc_lv<16> ap_ST_st4_fsm_3;
    static const sc_lv<16> ap_ST_st5_fsm_4;
    static const sc_lv<16> ap_ST_st6_fsm_5;
    static const sc_lv<16> ap_ST_st7_fsm_6;
    static const sc_lv<16> ap_ST_st8_fsm_7;
    static const sc_lv<16> ap_ST_st9_fsm_8;
    static const sc_lv<16> ap_ST_st10_fsm_9;
    static const sc_lv<16> ap_ST_st11_fsm_10;
    static const sc_lv<16> ap_ST_st12_fsm_11;
    static const sc_lv<16> ap_ST_st13_fsm_12;
    static const sc_lv<16> ap_ST_st14_fsm_13;
    static const sc_lv<16> ap_ST_st15_fsm_14;
    static const sc_lv<16> ap_ST_st16_fsm_15;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<64> ap_const_lv64_A;
    static const sc_lv<64> ap_const_lv64_9;
    static const sc_lv<64> ap_const_lv64_8;
    static const sc_lv<64> ap_const_lv64_7;
    static const sc_lv<64> ap_const_lv64_6;
    static const sc_lv<64> ap_const_lv64_5;
    static const sc_lv<64> ap_const_lv64_4;
    static const sc_lv<64> ap_const_lv64_3;
    static const sc_lv<64> ap_const_lv64_2;
    static const sc_lv<64> ap_const_lv64_1;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_D;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_105();
    void thread_ap_sig_bdd_112();
    void thread_ap_sig_bdd_121();
    void thread_ap_sig_bdd_128();
    void thread_ap_sig_bdd_137();
    void thread_ap_sig_bdd_144();
    void thread_ap_sig_bdd_186();
    void thread_ap_sig_bdd_223();
    void thread_ap_sig_bdd_241();
    void thread_ap_sig_bdd_274();
    void thread_ap_sig_bdd_32();
    void thread_ap_sig_bdd_361();
    void thread_ap_sig_bdd_73();
    void thread_ap_sig_bdd_80();
    void thread_ap_sig_bdd_88();
    void thread_ap_sig_bdd_96();
    void thread_ap_sig_cseq_ST_st10_fsm_9();
    void thread_ap_sig_cseq_ST_st11_fsm_10();
    void thread_ap_sig_cseq_ST_st12_fsm_11();
    void thread_ap_sig_cseq_ST_st13_fsm_12();
    void thread_ap_sig_cseq_ST_st14_fsm_13();
    void thread_ap_sig_cseq_ST_st15_fsm_14();
    void thread_ap_sig_cseq_ST_st16_fsm_15();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_ap_sig_cseq_ST_st7_fsm_6();
    void thread_ap_sig_cseq_ST_st8_fsm_7();
    void thread_ap_sig_cseq_ST_st9_fsm_8();
    void thread_c_address0();
    void thread_c_ce0();
    void thread_grp_fu_209_ce();
    void thread_grp_fu_209_p0();
    void thread_grp_fu_209_p1();
    void thread_grp_fu_225_ce();
    void thread_grp_fu_225_p0();
    void thread_grp_fu_225_p1();
    void thread_grp_fu_241_ce();
    void thread_grp_fu_241_p0();
    void thread_grp_fu_241_p1();
    void thread_grp_fu_257_ce();
    void thread_grp_fu_257_p0();
    void thread_grp_fu_257_p1();
    void thread_grp_fu_273_ce();
    void thread_grp_fu_273_p0();
    void thread_grp_fu_273_p1();
    void thread_grp_fu_293_ce();
    void thread_grp_fu_293_p0();
    void thread_grp_fu_293_p1();
    void thread_grp_fu_309_ce();
    void thread_grp_fu_309_p0();
    void thread_grp_fu_309_p1();
    void thread_grp_fu_324_ce();
    void thread_grp_fu_324_p0();
    void thread_grp_fu_324_p1();
    void thread_grp_fu_349_ce();
    void thread_grp_fu_349_p0();
    void thread_grp_fu_349_p1();
    void thread_grp_fu_365_ce();
    void thread_grp_fu_365_p0();
    void thread_grp_fu_365_p1();
    void thread_grp_fu_377_ce();
    void thread_grp_fu_377_p0();
    void thread_grp_fu_377_p1();
    void thread_tmp1_fu_279_p2();
    void thread_tmp2_fu_334_p2();
    void thread_tmp3_fu_330_p2();
    void thread_tmp4_fu_404_p2();
    void thread_tmp5_fu_391_p2();
    void thread_tmp6_fu_383_p2();
    void thread_tmp7_fu_399_p2();
    void thread_tmp8_fu_395_p2();
    void thread_tmp_fu_387_p2();
    void thread_x_ap_vld_in_sig();
    void thread_x_in_sig();
    void thread_y();
    void thread_y_ap_vld();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
