set_property SRC_FILE_INFO {cfile:/media/huutan86/Data/source_code/ECE527/testing_code/demo_1/demo_1.srcs/constrs_1/new/pin_assign.xdc rfile:../../../demo_1.srcs/constrs_1/new/pin_assign.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_load 0.000 [all_outputs]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_load 0.000 [all_outputs]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property LOAD 0 [get_ports led]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_load 0.000 [all_outputs]
