// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="array_io,hls_ip_2015_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k160tfbg484-1,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.400000,HLS_SYN_LAT=17,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1522,HLS_SYN_LUT=1090}" *)

module array_io (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        d_o_0_din,
        d_o_0_full_n,
        d_o_0_write,
        d_o_1_din,
        d_o_1_full_n,
        d_o_1_write,
        d_o_2_din,
        d_o_2_full_n,
        d_o_2_write,
        d_o_3_din,
        d_o_3_full_n,
        d_o_3_write,
        d_o_4_din,
        d_o_4_full_n,
        d_o_4_write,
        d_o_5_din,
        d_o_5_full_n,
        d_o_5_write,
        d_o_6_din,
        d_o_6_full_n,
        d_o_6_write,
        d_o_7_din,
        d_o_7_full_n,
        d_o_7_write,
        d_o_8_din,
        d_o_8_full_n,
        d_o_8_write,
        d_o_9_din,
        d_o_9_full_n,
        d_o_9_write,
        d_o_10_din,
        d_o_10_full_n,
        d_o_10_write,
        d_o_11_din,
        d_o_11_full_n,
        d_o_11_write,
        d_o_12_din,
        d_o_12_full_n,
        d_o_12_write,
        d_o_13_din,
        d_o_13_full_n,
        d_o_13_write,
        d_o_14_din,
        d_o_14_full_n,
        d_o_14_write,
        d_o_15_din,
        d_o_15_full_n,
        d_o_15_write,
        d_o_16_din,
        d_o_16_full_n,
        d_o_16_write,
        d_o_17_din,
        d_o_17_full_n,
        d_o_17_write,
        d_o_18_din,
        d_o_18_full_n,
        d_o_18_write,
        d_o_19_din,
        d_o_19_full_n,
        d_o_19_write,
        d_o_20_din,
        d_o_20_full_n,
        d_o_20_write,
        d_o_21_din,
        d_o_21_full_n,
        d_o_21_write,
        d_o_22_din,
        d_o_22_full_n,
        d_o_22_write,
        d_o_23_din,
        d_o_23_full_n,
        d_o_23_write,
        d_o_24_din,
        d_o_24_full_n,
        d_o_24_write,
        d_o_25_din,
        d_o_25_full_n,
        d_o_25_write,
        d_o_26_din,
        d_o_26_full_n,
        d_o_26_write,
        d_o_27_din,
        d_o_27_full_n,
        d_o_27_write,
        d_o_28_din,
        d_o_28_full_n,
        d_o_28_write,
        d_o_29_din,
        d_o_29_full_n,
        d_o_29_write,
        d_o_30_din,
        d_o_30_full_n,
        d_o_30_write,
        d_o_31_din,
        d_o_31_full_n,
        d_o_31_write,
        d_i_address0,
        d_i_ce0,
        d_i_q0,
        d_i_address1,
        d_i_ce1,
        d_i_q1
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 18'b1;
parameter    ap_ST_st2_fsm_1 = 18'b10;
parameter    ap_ST_st3_fsm_2 = 18'b100;
parameter    ap_ST_st4_fsm_3 = 18'b1000;
parameter    ap_ST_st5_fsm_4 = 18'b10000;
parameter    ap_ST_st6_fsm_5 = 18'b100000;
parameter    ap_ST_st7_fsm_6 = 18'b1000000;
parameter    ap_ST_st8_fsm_7 = 18'b10000000;
parameter    ap_ST_st9_fsm_8 = 18'b100000000;
parameter    ap_ST_st10_fsm_9 = 18'b1000000000;
parameter    ap_ST_st11_fsm_10 = 18'b10000000000;
parameter    ap_ST_st12_fsm_11 = 18'b100000000000;
parameter    ap_ST_st13_fsm_12 = 18'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 18'b10000000000000;
parameter    ap_ST_st15_fsm_14 = 18'b100000000000000;
parameter    ap_ST_st16_fsm_15 = 18'b1000000000000000;
parameter    ap_ST_st17_fsm_16 = 18'b10000000000000000;
parameter    ap_ST_st18_fsm_17 = 18'b100000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv64_0 = 64'b0000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv64_1 = 64'b1;
parameter    ap_const_lv64_2 = 64'b10;
parameter    ap_const_lv64_3 = 64'b11;
parameter    ap_const_lv64_4 = 64'b100;
parameter    ap_const_lv64_5 = 64'b101;
parameter    ap_const_lv64_6 = 64'b110;
parameter    ap_const_lv64_7 = 64'b111;
parameter    ap_const_lv64_8 = 64'b1000;
parameter    ap_const_lv64_9 = 64'b1001;
parameter    ap_const_lv64_A = 64'b1010;
parameter    ap_const_lv64_B = 64'b1011;
parameter    ap_const_lv64_C = 64'b1100;
parameter    ap_const_lv64_D = 64'b1101;
parameter    ap_const_lv64_E = 64'b1110;
parameter    ap_const_lv64_F = 64'b1111;
parameter    ap_const_lv64_10 = 64'b10000;
parameter    ap_const_lv64_11 = 64'b10001;
parameter    ap_const_lv64_12 = 64'b10010;
parameter    ap_const_lv64_13 = 64'b10011;
parameter    ap_const_lv64_14 = 64'b10100;
parameter    ap_const_lv64_15 = 64'b10101;
parameter    ap_const_lv64_16 = 64'b10110;
parameter    ap_const_lv64_17 = 64'b10111;
parameter    ap_const_lv64_18 = 64'b11000;
parameter    ap_const_lv64_19 = 64'b11001;
parameter    ap_const_lv64_1A = 64'b11010;
parameter    ap_const_lv64_1B = 64'b11011;
parameter    ap_const_lv64_1C = 64'b11100;
parameter    ap_const_lv64_1D = 64'b11101;
parameter    ap_const_lv64_1E = 64'b11110;
parameter    ap_const_lv64_1F = 64'b11111;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] d_o_0_din;
input   d_o_0_full_n;
output   d_o_0_write;
output  [15:0] d_o_1_din;
input   d_o_1_full_n;
output   d_o_1_write;
output  [15:0] d_o_2_din;
input   d_o_2_full_n;
output   d_o_2_write;
output  [15:0] d_o_3_din;
input   d_o_3_full_n;
output   d_o_3_write;
output  [15:0] d_o_4_din;
input   d_o_4_full_n;
output   d_o_4_write;
output  [15:0] d_o_5_din;
input   d_o_5_full_n;
output   d_o_5_write;
output  [15:0] d_o_6_din;
input   d_o_6_full_n;
output   d_o_6_write;
output  [15:0] d_o_7_din;
input   d_o_7_full_n;
output   d_o_7_write;
output  [15:0] d_o_8_din;
input   d_o_8_full_n;
output   d_o_8_write;
output  [15:0] d_o_9_din;
input   d_o_9_full_n;
output   d_o_9_write;
output  [15:0] d_o_10_din;
input   d_o_10_full_n;
output   d_o_10_write;
output  [15:0] d_o_11_din;
input   d_o_11_full_n;
output   d_o_11_write;
output  [15:0] d_o_12_din;
input   d_o_12_full_n;
output   d_o_12_write;
output  [15:0] d_o_13_din;
input   d_o_13_full_n;
output   d_o_13_write;
output  [15:0] d_o_14_din;
input   d_o_14_full_n;
output   d_o_14_write;
output  [15:0] d_o_15_din;
input   d_o_15_full_n;
output   d_o_15_write;
output  [15:0] d_o_16_din;
input   d_o_16_full_n;
output   d_o_16_write;
output  [15:0] d_o_17_din;
input   d_o_17_full_n;
output   d_o_17_write;
output  [15:0] d_o_18_din;
input   d_o_18_full_n;
output   d_o_18_write;
output  [15:0] d_o_19_din;
input   d_o_19_full_n;
output   d_o_19_write;
output  [15:0] d_o_20_din;
input   d_o_20_full_n;
output   d_o_20_write;
output  [15:0] d_o_21_din;
input   d_o_21_full_n;
output   d_o_21_write;
output  [15:0] d_o_22_din;
input   d_o_22_full_n;
output   d_o_22_write;
output  [15:0] d_o_23_din;
input   d_o_23_full_n;
output   d_o_23_write;
output  [15:0] d_o_24_din;
input   d_o_24_full_n;
output   d_o_24_write;
output  [15:0] d_o_25_din;
input   d_o_25_full_n;
output   d_o_25_write;
output  [15:0] d_o_26_din;
input   d_o_26_full_n;
output   d_o_26_write;
output  [15:0] d_o_27_din;
input   d_o_27_full_n;
output   d_o_27_write;
output  [15:0] d_o_28_din;
input   d_o_28_full_n;
output   d_o_28_write;
output  [15:0] d_o_29_din;
input   d_o_29_full_n;
output   d_o_29_write;
output  [15:0] d_o_30_din;
input   d_o_30_full_n;
output   d_o_30_write;
output  [15:0] d_o_31_din;
input   d_o_31_full_n;
output   d_o_31_write;
output  [4:0] d_i_address0;
output   d_i_ce0;
input  [15:0] d_i_q0;
output  [4:0] d_i_address1;
output   d_i_ce1;
input  [15:0] d_i_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg d_o_0_write;
reg d_o_1_write;
reg d_o_2_write;
reg d_o_3_write;
reg d_o_4_write;
reg d_o_5_write;
reg d_o_6_write;
reg d_o_7_write;
reg d_o_8_write;
reg d_o_9_write;
reg d_o_10_write;
reg d_o_11_write;
reg d_o_12_write;
reg d_o_13_write;
reg d_o_14_write;
reg d_o_15_write;
reg d_o_16_write;
reg d_o_17_write;
reg d_o_18_write;
reg d_o_19_write;
reg d_o_20_write;
reg d_o_21_write;
reg d_o_22_write;
reg d_o_23_write;
reg d_o_24_write;
reg d_o_25_write;
reg d_o_26_write;
reg d_o_27_write;
reg d_o_28_write;
reg d_o_29_write;
reg d_o_30_write;
reg d_o_31_write;
reg[4:0] d_i_address0;
reg d_i_ce0;
reg[4:0] d_i_address1;
reg d_i_ce1;
(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm = 18'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_34;
reg   [31:0] acc_0 = 32'b00000000000000000000000000000000;
reg   [31:0] acc_1 = 32'b00000000000000000000000000000000;
reg   [31:0] acc_2 = 32'b00000000000000000000000000000000;
reg   [31:0] acc_3 = 32'b00000000000000000000000000000000;
reg   [31:0] acc_4 = 32'b00000000000000000000000000000000;
reg   [31:0] acc_5 = 32'b00000000000000000000000000000000;
reg   [31:0] acc_6 = 32'b00000000000000000000000000000000;
reg   [31:0] acc_7 = 32'b00000000000000000000000000000000;
reg   [15:0] reg_688;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_192;
reg    ap_sig_cseq_ST_st16_fsm_15;
reg    ap_sig_bdd_199;
reg    ap_sig_cseq_ST_st17_fsm_16;
reg    ap_sig_bdd_207;
reg   [15:0] reg_692;
reg   [15:0] d_i_load_2_reg_1210;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_228;
reg   [15:0] d_i_load_3_reg_1215;
reg   [15:0] d_i_load_4_reg_1230;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_241;
reg   [15:0] d_i_load_5_reg_1235;
reg   [15:0] d_i_load_6_reg_1250;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_254;
reg   [15:0] d_i_load_7_reg_1255;
reg   [15:0] d_i_load_8_reg_1270;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_bdd_267;
reg   [15:0] d_i_load_9_reg_1275;
reg   [15:0] d_i_load_10_reg_1290;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_bdd_280;
reg   [15:0] d_i_load_11_reg_1295;
reg   [15:0] d_i_load_12_reg_1310;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_bdd_293;
reg   [15:0] d_i_load_13_reg_1315;
reg   [15:0] d_i_load_14_reg_1330;
reg    ap_sig_cseq_ST_st9_fsm_8;
reg    ap_sig_bdd_306;
reg   [15:0] d_i_load_15_reg_1335;
reg   [15:0] d_i_load_16_reg_1350;
reg    ap_sig_cseq_ST_st10_fsm_9;
reg    ap_sig_bdd_319;
reg   [15:0] d_i_load_17_reg_1355;
reg   [15:0] d_i_load_18_reg_1370;
reg    ap_sig_cseq_ST_st11_fsm_10;
reg    ap_sig_bdd_332;
reg   [15:0] d_i_load_19_reg_1375;
reg   [15:0] d_i_load_20_reg_1390;
reg    ap_sig_cseq_ST_st12_fsm_11;
reg    ap_sig_bdd_345;
reg   [15:0] d_i_load_21_reg_1395;
reg   [15:0] d_i_load_22_reg_1410;
reg    ap_sig_cseq_ST_st13_fsm_12;
reg    ap_sig_bdd_358;
reg   [15:0] d_i_load_23_reg_1415;
reg   [15:0] d_i_load_24_reg_1430;
reg    ap_sig_cseq_ST_st14_fsm_13;
reg    ap_sig_bdd_371;
reg   [15:0] d_i_load_25_reg_1435;
reg   [15:0] d_i_load_26_reg_1450;
reg    ap_sig_cseq_ST_st15_fsm_14;
reg    ap_sig_bdd_384;
reg   [15:0] d_i_load_27_reg_1455;
wire   [15:0] tmp_fu_710_p1;
reg   [15:0] tmp_reg_1470;
wire   [15:0] tmp_1_fu_728_p1;
reg   [15:0] tmp_1_reg_1475;
wire   [15:0] tmp_3_fu_745_p1;
reg   [15:0] tmp_3_reg_1480;
wire   [15:0] tmp_4_fu_762_p1;
reg   [15:0] tmp_4_reg_1485;
wire   [15:0] tmp_5_fu_779_p1;
reg   [15:0] tmp_5_reg_1490;
wire   [15:0] tmp_6_fu_796_p1;
reg   [15:0] tmp_6_reg_1495;
wire  signed [31:0] acc_6_loc_assign_2_fu_807_p2;
reg  signed [31:0] acc_6_loc_assign_2_reg_1500;
wire   [15:0] tmp_7_fu_813_p1;
reg   [15:0] tmp_7_reg_1505;
wire  signed [31:0] acc_7_loc_assign_2_fu_824_p2;
reg  signed [31:0] acc_7_loc_assign_2_reg_1510;
wire   [15:0] tmp_8_fu_830_p1;
reg   [15:0] tmp_8_reg_1515;
wire  signed [31:0] acc_0_loc_assign_1_fu_837_p2;
reg  signed [31:0] acc_0_loc_assign_1_reg_1520;
wire   [15:0] tmp_9_fu_843_p1;
reg   [15:0] tmp_9_reg_1525;
wire  signed [31:0] acc_1_loc_assign_1_fu_850_p2;
reg  signed [31:0] acc_1_loc_assign_1_reg_1530;
wire   [15:0] tmp_10_fu_856_p1;
reg   [15:0] tmp_10_reg_1535;
wire  signed [31:0] acc_2_loc_assign_1_fu_863_p2;
reg  signed [31:0] acc_2_loc_assign_1_reg_1540;
wire   [15:0] tmp_11_fu_869_p1;
reg   [15:0] tmp_11_reg_1545;
wire  signed [31:0] acc_3_loc_assign_1_fu_876_p2;
reg  signed [31:0] acc_3_loc_assign_1_reg_1550;
wire   [15:0] tmp_12_fu_882_p1;
reg   [15:0] tmp_12_reg_1555;
wire  signed [31:0] acc_4_loc_assign_1_fu_889_p2;
reg  signed [31:0] acc_4_loc_assign_1_reg_1560;
wire   [15:0] tmp_13_fu_895_p1;
reg   [15:0] tmp_13_reg_1565;
wire  signed [31:0] acc_5_loc_assign_1_fu_902_p2;
reg  signed [31:0] acc_5_loc_assign_1_reg_1570;
wire   [15:0] tmp_14_fu_908_p1;
reg   [15:0] tmp_14_reg_1575;
wire   [15:0] tmp_15_fu_920_p1;
reg   [15:0] tmp_15_reg_1590;
wire   [15:0] tmp_16_fu_932_p1;
reg   [15:0] tmp_16_reg_1595;
wire   [15:0] tmp_17_fu_944_p1;
reg   [15:0] tmp_17_reg_1600;
wire   [15:0] tmp_18_fu_956_p1;
reg   [15:0] tmp_18_reg_1605;
wire   [15:0] tmp_19_fu_968_p1;
reg   [15:0] tmp_19_reg_1610;
wire   [15:0] tmp_20_fu_980_p1;
reg   [15:0] tmp_20_reg_1615;
wire   [15:0] tmp_21_fu_992_p1;
reg   [15:0] tmp_21_reg_1620;
wire   [15:0] tmp_22_fu_1004_p1;
reg   [15:0] tmp_22_reg_1625;
wire  signed [31:0] acc_6_loc_fu_1011_p2;
reg  signed [31:0] acc_6_loc_reg_1630;
wire   [15:0] tmp_23_fu_1017_p1;
reg   [15:0] tmp_23_reg_1635;
wire  signed [31:0] acc_7_loc_fu_1024_p2;
reg  signed [31:0] acc_7_loc_reg_1640;
wire   [15:0] tmp_24_fu_1030_p1;
reg   [15:0] tmp_24_reg_1645;
wire   [15:0] tmp_25_fu_1049_p1;
reg   [15:0] tmp_25_reg_1650;
wire   [15:0] tmp_26_fu_1068_p1;
reg   [15:0] tmp_26_reg_1655;
wire   [15:0] tmp_27_fu_1087_p1;
reg   [15:0] tmp_27_reg_1660;
wire   [15:0] tmp_28_fu_1106_p1;
reg   [15:0] tmp_28_reg_1665;
wire   [15:0] tmp_29_fu_1126_p1;
reg   [15:0] tmp_29_reg_1670;
wire   [15:0] tmp_30_fu_1146_p1;
reg   [15:0] tmp_30_reg_1675;
reg    ap_sig_cseq_ST_st18_fsm_17;
reg    ap_sig_bdd_513;
reg    ap_sig_bdd_578;
wire  signed [31:0] temp_s_fu_1037_p2;
wire  signed [31:0] temp_1_fu_1056_p2;
wire  signed [31:0] temp_2_fu_1075_p2;
wire  signed [31:0] temp_3_fu_1094_p2;
wire  signed [31:0] temp_4_fu_1114_p2;
wire  signed [31:0] temp_5_fu_1134_p2;
wire  signed [31:0] temp_6_fu_1154_p2;
wire  signed [31:0] temp_7_fu_1174_p2;
wire  signed [31:0] tmp_2_fu_700_p1;
wire  signed [31:0] acc_0_loc_assign_2_fu_704_p2;
wire  signed [31:0] tmp_2_1_fu_718_p1;
wire  signed [31:0] acc_1_loc_assign_2_fu_722_p2;
wire  signed [31:0] tmp_2_2_fu_736_p1;
wire  signed [31:0] acc_2_loc_assign_2_fu_739_p2;
wire  signed [31:0] tmp_2_3_fu_753_p1;
wire  signed [31:0] acc_3_loc_assign_2_fu_756_p2;
wire  signed [31:0] tmp_2_4_fu_770_p1;
wire  signed [31:0] acc_4_loc_assign_2_fu_773_p2;
wire  signed [31:0] tmp_2_5_fu_787_p1;
wire  signed [31:0] acc_5_loc_assign_2_fu_790_p2;
wire  signed [31:0] tmp_2_6_fu_804_p1;
wire  signed [31:0] tmp_2_7_fu_821_p1;
wire  signed [31:0] tmp_2_8_fu_834_p1;
wire  signed [31:0] tmp_2_9_fu_847_p1;
wire  signed [31:0] tmp_2_s_fu_860_p1;
wire  signed [31:0] tmp_2_10_fu_873_p1;
wire  signed [31:0] tmp_2_11_fu_886_p1;
wire  signed [31:0] tmp_2_12_fu_899_p1;
wire  signed [31:0] tmp_2_13_fu_912_p1;
wire  signed [31:0] acc_6_loc_assign_1_fu_915_p2;
wire  signed [31:0] tmp_2_14_fu_924_p1;
wire  signed [31:0] acc_7_loc_assign_1_fu_927_p2;
wire  signed [31:0] tmp_2_15_fu_936_p1;
wire  signed [31:0] acc_0_loc_fu_939_p2;
wire  signed [31:0] tmp_2_16_fu_948_p1;
wire  signed [31:0] acc_1_loc_fu_951_p2;
wire  signed [31:0] tmp_2_17_fu_960_p1;
wire  signed [31:0] acc_2_loc_fu_963_p2;
wire  signed [31:0] tmp_2_18_fu_972_p1;
wire  signed [31:0] acc_3_loc_fu_975_p2;
wire  signed [31:0] tmp_2_19_fu_984_p1;
wire  signed [31:0] acc_4_loc_fu_987_p2;
wire  signed [31:0] tmp_2_20_fu_996_p1;
wire  signed [31:0] acc_5_loc_fu_999_p2;
wire  signed [31:0] tmp_2_21_fu_1008_p1;
wire  signed [31:0] tmp_2_22_fu_1021_p1;
wire  signed [31:0] tmp_2_23_fu_1034_p1;
wire  signed [31:0] tmp_2_24_fu_1053_p1;
wire  signed [31:0] tmp_2_25_fu_1072_p1;
wire  signed [31:0] tmp_2_26_fu_1091_p1;
wire  signed [31:0] tmp_2_27_fu_1110_p1;
wire  signed [31:0] tmp_2_28_fu_1130_p1;
wire  signed [31:0] tmp_2_29_fu_1150_p1;
wire  signed [31:0] tmp_2_30_fu_1170_p1;
reg   [17:0] ap_NS_fsm;




/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        acc_0 <= temp_s_fu_1037_p2;
        acc_1 <= temp_1_fu_1056_p2;
        acc_2 <= temp_2_fu_1075_p2;
        acc_3 <= temp_3_fu_1094_p2;
        acc_4 <= temp_4_fu_1114_p2;
        acc_5 <= temp_5_fu_1134_p2;
        acc_6_loc_reg_1630 <= acc_6_loc_fu_1011_p2;
        acc_7_loc_reg_1640 <= acc_7_loc_fu_1024_p2;
        tmp_15_reg_1590 <= tmp_15_fu_920_p1;
        tmp_16_reg_1595 <= tmp_16_fu_932_p1;
        tmp_17_reg_1600 <= tmp_17_fu_944_p1;
        tmp_18_reg_1605 <= tmp_18_fu_956_p1;
        tmp_19_reg_1610 <= tmp_19_fu_968_p1;
        tmp_20_reg_1615 <= tmp_20_fu_980_p1;
        tmp_21_reg_1620 <= tmp_21_fu_992_p1;
        tmp_22_reg_1625 <= tmp_22_fu_1004_p1;
        tmp_23_reg_1635 <= tmp_23_fu_1017_p1;
        tmp_24_reg_1645 <= tmp_24_fu_1030_p1;
        tmp_25_reg_1650 <= tmp_25_fu_1049_p1;
        tmp_26_reg_1655 <= tmp_26_fu_1068_p1;
        tmp_27_reg_1660 <= tmp_27_fu_1087_p1;
        tmp_28_reg_1665 <= tmp_28_fu_1106_p1;
        tmp_29_reg_1670 <= tmp_29_fu_1126_p1;
        tmp_30_reg_1675 <= tmp_30_fu_1146_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15)) begin
        acc_0_loc_assign_1_reg_1520 <= acc_0_loc_assign_1_fu_837_p2;
        acc_1_loc_assign_1_reg_1530 <= acc_1_loc_assign_1_fu_850_p2;
        acc_2_loc_assign_1_reg_1540 <= acc_2_loc_assign_1_fu_863_p2;
        acc_3_loc_assign_1_reg_1550 <= acc_3_loc_assign_1_fu_876_p2;
        acc_4_loc_assign_1_reg_1560 <= acc_4_loc_assign_1_fu_889_p2;
        acc_5_loc_assign_1_reg_1570 <= acc_5_loc_assign_1_fu_902_p2;
        acc_6_loc_assign_2_reg_1500 <= acc_6_loc_assign_2_fu_807_p2;
        acc_7_loc_assign_2_reg_1510 <= acc_7_loc_assign_2_fu_824_p2;
        tmp_10_reg_1535 <= tmp_10_fu_856_p1;
        tmp_11_reg_1545 <= tmp_11_fu_869_p1;
        tmp_12_reg_1555 <= tmp_12_fu_882_p1;
        tmp_13_reg_1565 <= tmp_13_fu_895_p1;
        tmp_14_reg_1575 <= tmp_14_fu_908_p1;
        tmp_1_reg_1475 <= tmp_1_fu_728_p1;
        tmp_3_reg_1480 <= tmp_3_fu_745_p1;
        tmp_4_reg_1485 <= tmp_4_fu_762_p1;
        tmp_5_reg_1490 <= tmp_5_fu_779_p1;
        tmp_6_reg_1495 <= tmp_6_fu_796_p1;
        tmp_7_reg_1505 <= tmp_7_fu_813_p1;
        tmp_8_reg_1515 <= tmp_8_fu_830_p1;
        tmp_9_reg_1525 <= tmp_9_fu_843_p1;
        tmp_reg_1470 <= tmp_fu_710_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        acc_6 <= temp_6_fu_1154_p2;
        acc_7 <= temp_7_fu_1174_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        d_i_load_10_reg_1290 <= d_i_q0;
        d_i_load_11_reg_1295 <= d_i_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        d_i_load_12_reg_1310 <= d_i_q0;
        d_i_load_13_reg_1315 <= d_i_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        d_i_load_14_reg_1330 <= d_i_q0;
        d_i_load_15_reg_1335 <= d_i_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        d_i_load_16_reg_1350 <= d_i_q0;
        d_i_load_17_reg_1355 <= d_i_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        d_i_load_18_reg_1370 <= d_i_q0;
        d_i_load_19_reg_1375 <= d_i_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        d_i_load_20_reg_1390 <= d_i_q0;
        d_i_load_21_reg_1395 <= d_i_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        d_i_load_22_reg_1410 <= d_i_q0;
        d_i_load_23_reg_1415 <= d_i_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        d_i_load_24_reg_1430 <= d_i_q0;
        d_i_load_25_reg_1435 <= d_i_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) begin
        d_i_load_26_reg_1450 <= d_i_q0;
        d_i_load_27_reg_1455 <= d_i_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        d_i_load_2_reg_1210 <= d_i_q0;
        d_i_load_3_reg_1215 <= d_i_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        d_i_load_4_reg_1230 <= d_i_q0;
        d_i_load_5_reg_1235 <= d_i_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        d_i_load_6_reg_1250 <= d_i_q0;
        d_i_load_7_reg_1255 <= d_i_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        d_i_load_8_reg_1270 <= d_i_q0;
        d_i_load_9_reg_1275 <= d_i_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | (ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16))) begin
        reg_688 <= d_i_q0;
        reg_692 <= d_i_q1;
    end
end

/// ap_done assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st10_fsm_9 assign process. ///
always @ (ap_sig_bdd_319)
begin
    if (ap_sig_bdd_319) begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st11_fsm_10 assign process. ///
always @ (ap_sig_bdd_332)
begin
    if (ap_sig_bdd_332) begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st12_fsm_11 assign process. ///
always @ (ap_sig_bdd_345)
begin
    if (ap_sig_bdd_345) begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st13_fsm_12 assign process. ///
always @ (ap_sig_bdd_358)
begin
    if (ap_sig_bdd_358) begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st14_fsm_13 assign process. ///
always @ (ap_sig_bdd_371)
begin
    if (ap_sig_bdd_371) begin
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st15_fsm_14 assign process. ///
always @ (ap_sig_bdd_384)
begin
    if (ap_sig_bdd_384) begin
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st16_fsm_15 assign process. ///
always @ (ap_sig_bdd_199)
begin
    if (ap_sig_bdd_199) begin
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st17_fsm_16 assign process. ///
always @ (ap_sig_bdd_207)
begin
    if (ap_sig_bdd_207) begin
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st18_fsm_17 assign process. ///
always @ (ap_sig_bdd_513)
begin
    if (ap_sig_bdd_513) begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_34)
begin
    if (ap_sig_bdd_34) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_192)
begin
    if (ap_sig_bdd_192) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st3_fsm_2 assign process. ///
always @ (ap_sig_bdd_228)
begin
    if (ap_sig_bdd_228) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st4_fsm_3 assign process. ///
always @ (ap_sig_bdd_241)
begin
    if (ap_sig_bdd_241) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st5_fsm_4 assign process. ///
always @ (ap_sig_bdd_254)
begin
    if (ap_sig_bdd_254) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st6_fsm_5 assign process. ///
always @ (ap_sig_bdd_267)
begin
    if (ap_sig_bdd_267) begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st7_fsm_6 assign process. ///
always @ (ap_sig_bdd_280)
begin
    if (ap_sig_bdd_280) begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st8_fsm_7 assign process. ///
always @ (ap_sig_bdd_293)
begin
    if (ap_sig_bdd_293) begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st9_fsm_8 assign process. ///
always @ (ap_sig_bdd_306)
begin
    if (ap_sig_bdd_306) begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    end
end

/// d_i_address0 assign process. ///
always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st14_fsm_13 or ap_sig_cseq_ST_st15_fsm_14)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15)) begin
        d_i_address0 = ap_const_lv64_1E;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) begin
        d_i_address0 = ap_const_lv64_1C;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        d_i_address0 = ap_const_lv64_1A;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        d_i_address0 = ap_const_lv64_18;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        d_i_address0 = ap_const_lv64_16;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        d_i_address0 = ap_const_lv64_14;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        d_i_address0 = ap_const_lv64_12;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        d_i_address0 = ap_const_lv64_10;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        d_i_address0 = ap_const_lv64_E;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        d_i_address0 = ap_const_lv64_C;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        d_i_address0 = ap_const_lv64_A;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        d_i_address0 = ap_const_lv64_8;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        d_i_address0 = ap_const_lv64_6;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        d_i_address0 = ap_const_lv64_4;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        d_i_address0 = ap_const_lv64_2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) begin
        d_i_address0 = ap_const_lv64_0;
    end else begin
        d_i_address0 = 'bx;
    end
end

/// d_i_address1 assign process. ///
always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st14_fsm_13 or ap_sig_cseq_ST_st15_fsm_14)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15)) begin
        d_i_address1 = ap_const_lv64_1F;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) begin
        d_i_address1 = ap_const_lv64_1D;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        d_i_address1 = ap_const_lv64_1B;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        d_i_address1 = ap_const_lv64_19;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        d_i_address1 = ap_const_lv64_17;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        d_i_address1 = ap_const_lv64_15;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        d_i_address1 = ap_const_lv64_13;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        d_i_address1 = ap_const_lv64_11;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        d_i_address1 = ap_const_lv64_F;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        d_i_address1 = ap_const_lv64_D;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        d_i_address1 = ap_const_lv64_B;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        d_i_address1 = ap_const_lv64_9;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        d_i_address1 = ap_const_lv64_7;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        d_i_address1 = ap_const_lv64_5;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        d_i_address1 = ap_const_lv64_3;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) begin
        d_i_address1 = ap_const_lv64_1;
    end else begin
        d_i_address1 = 'bx;
    end
end

/// d_i_ce0 assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st14_fsm_13 or ap_sig_cseq_ST_st15_fsm_14)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0)) | (ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) | (ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) | (ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | (ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) | (ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) | (ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14))) begin
        d_i_ce0 = ap_const_logic_1;
    end else begin
        d_i_ce0 = ap_const_logic_0;
    end
end

/// d_i_ce1 assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st3_fsm_2 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st7_fsm_6 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st14_fsm_13 or ap_sig_cseq_ST_st15_fsm_14)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0)) | (ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) | (ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) | (ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) | (ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | (ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) | (ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) | (ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14))) begin
        d_i_ce1 = ap_const_logic_1;
    end else begin
        d_i_ce1 = ap_const_logic_0;
    end
end

/// d_o_0_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_0_write = ap_const_logic_1;
    end else begin
        d_o_0_write = ap_const_logic_0;
    end
end

/// d_o_10_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_10_write = ap_const_logic_1;
    end else begin
        d_o_10_write = ap_const_logic_0;
    end
end

/// d_o_11_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_11_write = ap_const_logic_1;
    end else begin
        d_o_11_write = ap_const_logic_0;
    end
end

/// d_o_12_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_12_write = ap_const_logic_1;
    end else begin
        d_o_12_write = ap_const_logic_0;
    end
end

/// d_o_13_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_13_write = ap_const_logic_1;
    end else begin
        d_o_13_write = ap_const_logic_0;
    end
end

/// d_o_14_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_14_write = ap_const_logic_1;
    end else begin
        d_o_14_write = ap_const_logic_0;
    end
end

/// d_o_15_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_15_write = ap_const_logic_1;
    end else begin
        d_o_15_write = ap_const_logic_0;
    end
end

/// d_o_16_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_16_write = ap_const_logic_1;
    end else begin
        d_o_16_write = ap_const_logic_0;
    end
end

/// d_o_17_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_17_write = ap_const_logic_1;
    end else begin
        d_o_17_write = ap_const_logic_0;
    end
end

/// d_o_18_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_18_write = ap_const_logic_1;
    end else begin
        d_o_18_write = ap_const_logic_0;
    end
end

/// d_o_19_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_19_write = ap_const_logic_1;
    end else begin
        d_o_19_write = ap_const_logic_0;
    end
end

/// d_o_1_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_1_write = ap_const_logic_1;
    end else begin
        d_o_1_write = ap_const_logic_0;
    end
end

/// d_o_20_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_20_write = ap_const_logic_1;
    end else begin
        d_o_20_write = ap_const_logic_0;
    end
end

/// d_o_21_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_21_write = ap_const_logic_1;
    end else begin
        d_o_21_write = ap_const_logic_0;
    end
end

/// d_o_22_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_22_write = ap_const_logic_1;
    end else begin
        d_o_22_write = ap_const_logic_0;
    end
end

/// d_o_23_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_23_write = ap_const_logic_1;
    end else begin
        d_o_23_write = ap_const_logic_0;
    end
end

/// d_o_24_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_24_write = ap_const_logic_1;
    end else begin
        d_o_24_write = ap_const_logic_0;
    end
end

/// d_o_25_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_25_write = ap_const_logic_1;
    end else begin
        d_o_25_write = ap_const_logic_0;
    end
end

/// d_o_26_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_26_write = ap_const_logic_1;
    end else begin
        d_o_26_write = ap_const_logic_0;
    end
end

/// d_o_27_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_27_write = ap_const_logic_1;
    end else begin
        d_o_27_write = ap_const_logic_0;
    end
end

/// d_o_28_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_28_write = ap_const_logic_1;
    end else begin
        d_o_28_write = ap_const_logic_0;
    end
end

/// d_o_29_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_29_write = ap_const_logic_1;
    end else begin
        d_o_29_write = ap_const_logic_0;
    end
end

/// d_o_2_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_2_write = ap_const_logic_1;
    end else begin
        d_o_2_write = ap_const_logic_0;
    end
end

/// d_o_30_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_30_write = ap_const_logic_1;
    end else begin
        d_o_30_write = ap_const_logic_0;
    end
end

/// d_o_31_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_31_write = ap_const_logic_1;
    end else begin
        d_o_31_write = ap_const_logic_0;
    end
end

/// d_o_3_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_3_write = ap_const_logic_1;
    end else begin
        d_o_3_write = ap_const_logic_0;
    end
end

/// d_o_4_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_4_write = ap_const_logic_1;
    end else begin
        d_o_4_write = ap_const_logic_0;
    end
end

/// d_o_5_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_5_write = ap_const_logic_1;
    end else begin
        d_o_5_write = ap_const_logic_0;
    end
end

/// d_o_6_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_6_write = ap_const_logic_1;
    end else begin
        d_o_6_write = ap_const_logic_0;
    end
end

/// d_o_7_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_7_write = ap_const_logic_1;
    end else begin
        d_o_7_write = ap_const_logic_0;
    end
end

/// d_o_8_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_8_write = ap_const_logic_1;
    end else begin
        d_o_8_write = ap_const_logic_0;
    end
end

/// d_o_9_write assign process. ///
always @ (ap_sig_cseq_ST_st18_fsm_17 or ap_sig_bdd_578)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) & ~ap_sig_bdd_578)) begin
        d_o_9_write = ap_const_logic_1;
    end else begin
        d_o_9_write = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_start or ap_CS_fsm or ap_sig_bdd_578)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        ap_ST_st6_fsm_5 : 
        begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st7_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st8_fsm_7;
        end
        ap_ST_st8_fsm_7 : 
        begin
            ap_NS_fsm = ap_ST_st9_fsm_8;
        end
        ap_ST_st9_fsm_8 : 
        begin
            ap_NS_fsm = ap_ST_st10_fsm_9;
        end
        ap_ST_st10_fsm_9 : 
        begin
            ap_NS_fsm = ap_ST_st11_fsm_10;
        end
        ap_ST_st11_fsm_10 : 
        begin
            ap_NS_fsm = ap_ST_st12_fsm_11;
        end
        ap_ST_st12_fsm_11 : 
        begin
            ap_NS_fsm = ap_ST_st13_fsm_12;
        end
        ap_ST_st13_fsm_12 : 
        begin
            ap_NS_fsm = ap_ST_st14_fsm_13;
        end
        ap_ST_st14_fsm_13 : 
        begin
            ap_NS_fsm = ap_ST_st15_fsm_14;
        end
        ap_ST_st15_fsm_14 : 
        begin
            ap_NS_fsm = ap_ST_st16_fsm_15;
        end
        ap_ST_st16_fsm_15 : 
        begin
            ap_NS_fsm = ap_ST_st17_fsm_16;
        end
        ap_ST_st17_fsm_16 : 
        begin
            ap_NS_fsm = ap_ST_st18_fsm_17;
        end
        ap_ST_st18_fsm_17 : 
        begin
            if (~ap_sig_bdd_578) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st18_fsm_17;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_0_loc_assign_1_fu_837_p2 = ($signed(acc_0_loc_assign_2_fu_704_p2) + $signed(tmp_2_8_fu_834_p1));
assign acc_0_loc_assign_2_fu_704_p2 = ($signed(acc_0) + $signed(tmp_2_fu_700_p1));
assign acc_0_loc_fu_939_p2 = ($signed(acc_0_loc_assign_1_reg_1520) + $signed(tmp_2_15_fu_936_p1));
assign acc_1_loc_assign_1_fu_850_p2 = ($signed(acc_1_loc_assign_2_fu_722_p2) + $signed(tmp_2_9_fu_847_p1));
assign acc_1_loc_assign_2_fu_722_p2 = ($signed(acc_1) + $signed(tmp_2_1_fu_718_p1));
assign acc_1_loc_fu_951_p2 = ($signed(acc_1_loc_assign_1_reg_1530) + $signed(tmp_2_16_fu_948_p1));
assign acc_2_loc_assign_1_fu_863_p2 = ($signed(acc_2_loc_assign_2_fu_739_p2) + $signed(tmp_2_s_fu_860_p1));
assign acc_2_loc_assign_2_fu_739_p2 = ($signed(acc_2) + $signed(tmp_2_2_fu_736_p1));
assign acc_2_loc_fu_963_p2 = ($signed(acc_2_loc_assign_1_reg_1540) + $signed(tmp_2_17_fu_960_p1));
assign acc_3_loc_assign_1_fu_876_p2 = ($signed(acc_3_loc_assign_2_fu_756_p2) + $signed(tmp_2_10_fu_873_p1));
assign acc_3_loc_assign_2_fu_756_p2 = ($signed(acc_3) + $signed(tmp_2_3_fu_753_p1));
assign acc_3_loc_fu_975_p2 = ($signed(acc_3_loc_assign_1_reg_1550) + $signed(tmp_2_18_fu_972_p1));
assign acc_4_loc_assign_1_fu_889_p2 = ($signed(acc_4_loc_assign_2_fu_773_p2) + $signed(tmp_2_11_fu_886_p1));
assign acc_4_loc_assign_2_fu_773_p2 = ($signed(acc_4) + $signed(tmp_2_4_fu_770_p1));
assign acc_4_loc_fu_987_p2 = ($signed(acc_4_loc_assign_1_reg_1560) + $signed(tmp_2_19_fu_984_p1));
assign acc_5_loc_assign_1_fu_902_p2 = ($signed(acc_5_loc_assign_2_fu_790_p2) + $signed(tmp_2_12_fu_899_p1));
assign acc_5_loc_assign_2_fu_790_p2 = ($signed(acc_5) + $signed(tmp_2_5_fu_787_p1));
assign acc_5_loc_fu_999_p2 = ($signed(acc_5_loc_assign_1_reg_1570) + $signed(tmp_2_20_fu_996_p1));
assign acc_6_loc_assign_1_fu_915_p2 = ($signed(acc_6_loc_assign_2_reg_1500) + $signed(tmp_2_13_fu_912_p1));
assign acc_6_loc_assign_2_fu_807_p2 = ($signed(acc_6) + $signed(tmp_2_6_fu_804_p1));
assign acc_6_loc_fu_1011_p2 = ($signed(acc_6_loc_assign_1_fu_915_p2) + $signed(tmp_2_21_fu_1008_p1));
assign acc_7_loc_assign_1_fu_927_p2 = ($signed(acc_7_loc_assign_2_reg_1510) + $signed(tmp_2_14_fu_924_p1));
assign acc_7_loc_assign_2_fu_824_p2 = ($signed(acc_7) + $signed(tmp_2_7_fu_821_p1));
assign acc_7_loc_fu_1024_p2 = ($signed(acc_7_loc_assign_1_fu_927_p2) + $signed(tmp_2_22_fu_1021_p1));

/// ap_sig_bdd_192 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_192 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

/// ap_sig_bdd_199 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_199 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_F]);
end

/// ap_sig_bdd_207 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_207 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_10]);
end

/// ap_sig_bdd_228 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_228 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_241 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_241 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_254 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_254 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

/// ap_sig_bdd_267 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_267 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end

/// ap_sig_bdd_280 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_280 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end

/// ap_sig_bdd_293 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_293 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_7]);
end

/// ap_sig_bdd_306 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_306 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_8]);
end

/// ap_sig_bdd_319 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_319 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_9]);
end

/// ap_sig_bdd_332 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_332 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_A]);
end

/// ap_sig_bdd_34 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_34 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_345 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_345 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_B]);
end

/// ap_sig_bdd_358 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_358 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_C]);
end

/// ap_sig_bdd_371 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_371 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_D]);
end

/// ap_sig_bdd_384 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_384 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_E]);
end

/// ap_sig_bdd_513 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_513 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_11]);
end

/// ap_sig_bdd_578 assign process. ///
always @ (d_o_0_full_n or d_o_1_full_n or d_o_2_full_n or d_o_3_full_n or d_o_4_full_n or d_o_5_full_n or d_o_6_full_n or d_o_7_full_n or d_o_8_full_n or d_o_9_full_n or d_o_10_full_n or d_o_11_full_n or d_o_12_full_n or d_o_13_full_n or d_o_14_full_n or d_o_15_full_n or d_o_16_full_n or d_o_17_full_n or d_o_18_full_n or d_o_19_full_n or d_o_20_full_n or d_o_21_full_n or d_o_22_full_n or d_o_23_full_n or d_o_24_full_n or d_o_25_full_n or d_o_26_full_n or d_o_27_full_n or d_o_28_full_n or d_o_29_full_n or d_o_30_full_n or d_o_31_full_n)
begin
    ap_sig_bdd_578 = ((d_o_0_full_n == ap_const_logic_0) | (d_o_1_full_n == ap_const_logic_0) | (d_o_2_full_n == ap_const_logic_0) | (d_o_3_full_n == ap_const_logic_0) | (d_o_4_full_n == ap_const_logic_0) | (d_o_5_full_n == ap_const_logic_0) | (d_o_6_full_n == ap_const_logic_0) | (d_o_7_full_n == ap_const_logic_0) | (d_o_8_full_n == ap_const_logic_0) | (d_o_9_full_n == ap_const_logic_0) | (d_o_10_full_n == ap_const_logic_0) | (d_o_11_full_n == ap_const_logic_0) | (d_o_12_full_n == ap_const_logic_0) | (d_o_13_full_n == ap_const_logic_0) | (d_o_14_full_n == ap_const_logic_0) | (d_o_15_full_n == ap_const_logic_0) | (d_o_16_full_n == ap_const_logic_0) | (d_o_17_full_n == ap_const_logic_0) | (d_o_18_full_n == ap_const_logic_0) | (d_o_19_full_n == ap_const_logic_0) | (d_o_20_full_n == ap_const_logic_0) | (d_o_21_full_n == ap_const_logic_0) | (d_o_22_full_n == ap_const_logic_0) | (d_o_23_full_n == ap_const_logic_0) | (d_o_24_full_n == ap_const_logic_0) | (d_o_25_full_n == ap_const_logic_0) | (d_o_26_full_n == ap_const_logic_0) | (d_o_27_full_n == ap_const_logic_0) | (d_o_28_full_n == ap_const_logic_0) | (d_o_29_full_n == ap_const_logic_0) | (d_o_30_full_n == ap_const_logic_0) | (d_o_31_full_n == ap_const_logic_0));
end
assign d_o_0_din = tmp_reg_1470;
assign d_o_10_din = tmp_11_reg_1545;
assign d_o_11_din = tmp_12_reg_1555;
assign d_o_12_din = tmp_13_reg_1565;
assign d_o_13_din = tmp_14_reg_1575;
assign d_o_14_din = tmp_15_reg_1590;
assign d_o_15_din = tmp_16_reg_1595;
assign d_o_16_din = tmp_17_reg_1600;
assign d_o_17_din = tmp_18_reg_1605;
assign d_o_18_din = tmp_19_reg_1610;
assign d_o_19_din = tmp_20_reg_1615;
assign d_o_1_din = tmp_1_reg_1475;
assign d_o_20_din = tmp_21_reg_1620;
assign d_o_21_din = tmp_22_reg_1625;
assign d_o_22_din = tmp_23_reg_1635;
assign d_o_23_din = tmp_24_reg_1645;
assign d_o_24_din = tmp_25_reg_1650;
assign d_o_25_din = tmp_26_reg_1655;
assign d_o_26_din = tmp_27_reg_1660;
assign d_o_27_din = tmp_28_reg_1665;
assign d_o_28_din = tmp_29_reg_1670;
assign d_o_29_din = tmp_30_reg_1675;
assign d_o_2_din = tmp_3_reg_1480;
assign d_o_30_din = temp_6_fu_1154_p2[15:0];
assign d_o_31_din = temp_7_fu_1174_p2[15:0];
assign d_o_3_din = tmp_4_reg_1485;
assign d_o_4_din = tmp_5_reg_1490;
assign d_o_5_din = tmp_6_reg_1495;
assign d_o_6_din = tmp_7_reg_1505;
assign d_o_7_din = tmp_8_reg_1515;
assign d_o_8_din = tmp_9_reg_1525;
assign d_o_9_din = tmp_10_reg_1535;
assign temp_1_fu_1056_p2 = ($signed(acc_1_loc_fu_951_p2) + $signed(tmp_2_24_fu_1053_p1));
assign temp_2_fu_1075_p2 = ($signed(acc_2_loc_fu_963_p2) + $signed(tmp_2_25_fu_1072_p1));
assign temp_3_fu_1094_p2 = ($signed(acc_3_loc_fu_975_p2) + $signed(tmp_2_26_fu_1091_p1));
assign temp_4_fu_1114_p2 = ($signed(acc_4_loc_fu_987_p2) + $signed(tmp_2_27_fu_1110_p1));
assign temp_5_fu_1134_p2 = ($signed(acc_5_loc_fu_999_p2) + $signed(tmp_2_28_fu_1130_p1));
assign temp_6_fu_1154_p2 = ($signed(acc_6_loc_reg_1630) + $signed(tmp_2_29_fu_1150_p1));
assign temp_7_fu_1174_p2 = ($signed(acc_7_loc_reg_1640) + $signed(tmp_2_30_fu_1170_p1));
assign temp_s_fu_1037_p2 = ($signed(acc_0_loc_fu_939_p2) + $signed(tmp_2_23_fu_1034_p1));
assign tmp_10_fu_856_p1 = acc_1_loc_assign_1_fu_850_p2[15:0];
assign tmp_11_fu_869_p1 = acc_2_loc_assign_1_fu_863_p2[15:0];
assign tmp_12_fu_882_p1 = acc_3_loc_assign_1_fu_876_p2[15:0];
assign tmp_13_fu_895_p1 = acc_4_loc_assign_1_fu_889_p2[15:0];
assign tmp_14_fu_908_p1 = acc_5_loc_assign_1_fu_902_p2[15:0];
assign tmp_15_fu_920_p1 = acc_6_loc_assign_1_fu_915_p2[15:0];
assign tmp_16_fu_932_p1 = acc_7_loc_assign_1_fu_927_p2[15:0];
assign tmp_17_fu_944_p1 = acc_0_loc_fu_939_p2[15:0];
assign tmp_18_fu_956_p1 = acc_1_loc_fu_951_p2[15:0];
assign tmp_19_fu_968_p1 = acc_2_loc_fu_963_p2[15:0];
assign tmp_1_fu_728_p1 = acc_1_loc_assign_2_fu_722_p2[15:0];
assign tmp_20_fu_980_p1 = acc_3_loc_fu_975_p2[15:0];
assign tmp_21_fu_992_p1 = acc_4_loc_fu_987_p2[15:0];
assign tmp_22_fu_1004_p1 = acc_5_loc_fu_999_p2[15:0];
assign tmp_23_fu_1017_p1 = acc_6_loc_fu_1011_p2[15:0];
assign tmp_24_fu_1030_p1 = acc_7_loc_fu_1024_p2[15:0];
assign tmp_25_fu_1049_p1 = temp_s_fu_1037_p2[15:0];
assign tmp_26_fu_1068_p1 = temp_1_fu_1056_p2[15:0];
assign tmp_27_fu_1087_p1 = temp_2_fu_1075_p2[15:0];
assign tmp_28_fu_1106_p1 = temp_3_fu_1094_p2[15:0];
assign tmp_29_fu_1126_p1 = temp_4_fu_1114_p2[15:0];
assign tmp_2_10_fu_873_p1 = $signed(d_i_load_11_reg_1295);
assign tmp_2_11_fu_886_p1 = $signed(d_i_load_12_reg_1310);
assign tmp_2_12_fu_899_p1 = $signed(d_i_load_13_reg_1315);
assign tmp_2_13_fu_912_p1 = $signed(d_i_load_14_reg_1330);
assign tmp_2_14_fu_924_p1 = $signed(d_i_load_15_reg_1335);
assign tmp_2_15_fu_936_p1 = $signed(d_i_load_16_reg_1350);
assign tmp_2_16_fu_948_p1 = $signed(d_i_load_17_reg_1355);
assign tmp_2_17_fu_960_p1 = $signed(d_i_load_18_reg_1370);
assign tmp_2_18_fu_972_p1 = $signed(d_i_load_19_reg_1375);
assign tmp_2_19_fu_984_p1 = $signed(d_i_load_20_reg_1390);
assign tmp_2_1_fu_718_p1 = $signed(reg_692);
assign tmp_2_20_fu_996_p1 = $signed(d_i_load_21_reg_1395);
assign tmp_2_21_fu_1008_p1 = $signed(d_i_load_22_reg_1410);
assign tmp_2_22_fu_1021_p1 = $signed(d_i_load_23_reg_1415);
assign tmp_2_23_fu_1034_p1 = $signed(d_i_load_24_reg_1430);
assign tmp_2_24_fu_1053_p1 = $signed(d_i_load_25_reg_1435);
assign tmp_2_25_fu_1072_p1 = $signed(d_i_load_26_reg_1450);
assign tmp_2_26_fu_1091_p1 = $signed(d_i_load_27_reg_1455);
assign tmp_2_27_fu_1110_p1 = $signed(reg_688);
assign tmp_2_28_fu_1130_p1 = $signed(reg_692);
assign tmp_2_29_fu_1150_p1 = $signed(reg_688);
assign tmp_2_2_fu_736_p1 = $signed(d_i_load_2_reg_1210);
assign tmp_2_30_fu_1170_p1 = $signed(reg_692);
assign tmp_2_3_fu_753_p1 = $signed(d_i_load_3_reg_1215);
assign tmp_2_4_fu_770_p1 = $signed(d_i_load_4_reg_1230);
assign tmp_2_5_fu_787_p1 = $signed(d_i_load_5_reg_1235);
assign tmp_2_6_fu_804_p1 = $signed(d_i_load_6_reg_1250);
assign tmp_2_7_fu_821_p1 = $signed(d_i_load_7_reg_1255);
assign tmp_2_8_fu_834_p1 = $signed(d_i_load_8_reg_1270);
assign tmp_2_9_fu_847_p1 = $signed(d_i_load_9_reg_1275);
assign tmp_2_fu_700_p1 = $signed(reg_688);
assign tmp_2_s_fu_860_p1 = $signed(d_i_load_10_reg_1290);
assign tmp_30_fu_1146_p1 = temp_5_fu_1134_p2[15:0];
assign tmp_3_fu_745_p1 = acc_2_loc_assign_2_fu_739_p2[15:0];
assign tmp_4_fu_762_p1 = acc_3_loc_assign_2_fu_756_p2[15:0];
assign tmp_5_fu_779_p1 = acc_4_loc_assign_2_fu_773_p2[15:0];
assign tmp_6_fu_796_p1 = acc_5_loc_assign_2_fu_790_p2[15:0];
assign tmp_7_fu_813_p1 = acc_6_loc_assign_2_fu_807_p2[15:0];
assign tmp_8_fu_830_p1 = acc_7_loc_assign_2_fu_824_p2[15:0];
assign tmp_9_fu_843_p1 = acc_0_loc_assign_1_fu_837_p2[15:0];
assign tmp_fu_710_p1 = acc_0_loc_assign_2_fu_704_p2[15:0];


endmodule //array_io

